---
name: Package Release
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: --no-color -q
          annotate: warning

      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Webhook Notification
        if: failure()
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        env:
          JOB_STATUS: ${{ job.status }}
          HOOK_OS_NAME: ${{ runner.os }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WORKFLOW_NAME: ${{ github.workflow }}
